channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - numpy
  - pandas
  - pyjwt=2.4.0
  - spacy-model-en_core_web_lg
  - pip:
      - beautifulsoup4==4.11.1
      - talon==1.4.4
      - jwt==1.3.1
      - typing-extensions==4.5.0
      - urllib3==1.26.14
      - spacy==3.4.1
